<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
if(!Schema::hasTable('clients'))Schema::create('clients',function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->nullable();$t->string('phone')->nullable();$t->string('preferred_language',2)->default('pt');$t->text('notes')->nullable();$t->timestamps();});
Schema::create('service_jobs',function(Blueprint $t){$t->id();$t->foreignId('client_id')->nullable()->constrained()->nullOnDelete();$t->string('reference')->unique();$t->string('title');$t->string('service');$t->string('status')->default('planned');$t->unsignedTinyInteger('progress')->default(0);$t->string('location')->nullable();$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->text('notes')->nullable();$t->timestamps();});
Schema::create('appointments',function(Blueprint $t){$t->id();$t->foreignId('client_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('job_id')->nullable()->constrained('service_jobs')->nullOnDelete();$t->string('title');$t->dateTime('starts_at');$t->dateTime('ends_at');$t->string('location')->nullable();$t->string('status')->default('scheduled');$t->string('google_event_id')->nullable();$t->text('notes')->nullable();$t->timestamps();});
Schema::create('material_items',function(Blueprint $t){$t->id();$t->foreignId('job_id')->constrained('service_jobs')->cascadeOnDelete();$t->string('name');$t->decimal('quantity',10,2)->default(1);$t->string('unit')->default('un.');$t->decimal('unit_cost',10,2)->nullable();$t->string('status')->default('needed');$t->string('supplier')->nullable();$t->date('purchased_at')->nullable();$t->timestamps();});
Schema::create('customer_messages',function(Blueprint $t){$t->id();$t->foreignId('client_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('quote_request_id')->nullable()->constrained()->nullOnDelete();$t->string('channel')->default('website');$t->string('subject')->nullable();$t->text('body');$t->string('status')->default('unread');$t->timestamps();});}
public function down():void{foreach(['customer_messages','material_items','appointments','service_jobs','clients']as$table)Schema::dropIfExists($table);}};
